In [4]:
import pandas as pd
import numpy as np

In [88]:
sdf=pd.read_csv('timeSeries_classe_10.csv', index_col='node')
sdf

classe      30.0      60.0      90.0     120.0     150.0  \
node                                                                        
epsilon_31            2  0.001381  0.002936  0.004601  0.006681  0.010590   
epsilon_33            2  0.001945  0.004156  0.006397  0.009004  0.011478   
epsilon_43            7  0.002191  0.004675  0.007056  0.009447  0.011824   
epsilon_44            5  0.001763  0.003763  0.005622  0.007351  0.008987   
epsilon_45            7  0.002042  0.004384  0.006683  0.009056  0.011470   
...                 ...       ...       ...       ...       ...       ...   
epsilon_2342475       0  0.001128  0.002374  0.003603  0.004883  0.006219   
epsilon_2342476       0  0.001128  0.002374  0.003603  0.004884  0.006221   
epsilon_2342523       9  0.001062  0.002274  0.003484  0.004767  0.006122   
epsilon_2342524       9  0.001051  0.002250  0.003450  0.004725  0.006074   
epsilon_2342525       9  0.001064  0.002279  0.003492  0.004778  0.006137   

                    180.0     210.0     240.0     270.0  ...    1230.0  \
node                                                     ...             
epsilon_31       0.016683  0.022709  0.028125  0.033974  ...  0.039911   
epsilon_33       0.014675  0.020829  0.026554  0.032728  ...  0.037888   
epsilon_43       0.014021  0.016233  0.018997  0.021656  ...  0.019458   
epsilon_44       0.010551  0.012098  0.013961  0.016068  ...  0.014890   
epsilon_45       0.013742  0.016055  0.018649  0.021334  ...  0.020268   
...                   ...       ...       ...       ...  ...       ...   
epsilon_2342475  0.007688  0.009240  0.010877  0.012730  ...  0.012697   
epsilon_2342476  0.007691  0.009244  0.010882  0.012737  ...  0.012705   
epsilon_2342523  0.007580  0.009125  0.010755  0.012478  ...  0.012163   
epsilon_2342524  0.007530  0.009076  0.010706  0.012435  ...  0.012153   
epsilon_2342525  0.007600  0.009148  0.010781  0.012508  ...  0.012186   

                   1830.0    2430.0    3030.0    3630.0    3690.0    3750.0  \
node                                                                          
epsilon_31       0.039912  0.039912  0.039912  0.039912  0.036154  0.032024   
epsilon_33       0.037888  0.037888  0.037887  0.037887  0.032482  0.026983   
epsilon_43       0.019458  0.019458  0.019458  0.019458  0.013356  0.008043   
epsilon_44       0.014891  0.014892  0.014892  0.014892  0.009960  0.006351   
epsilon_45       0.020266  0.020265  0.020265  0.020265  0.014261  0.008865   
...                   ...       ...       ...       ...       ...       ...   
epsilon_2342475  0.012697  0.012697  0.012697  0.012697  0.009548  0.006790   
epsilon_2342476  0.012705  0.012705  0.012705  0.012705  0.009553  0.006793   
epsilon_2342523  0.012163  0.012163  0.012163  0.012163  0.009099  0.006337   
epsilon_2342524  0.012153  0.012153  0.012153  0.012153  0.009116  0.006380   
epsilon_2342525  0.012186  0.012186  0.012186  0.012186  0.009116  0.006351   

                   3810.0    3870.0    3930.0  
node                                           
epsilon_31       0.025721  0.018334  0.011430  
epsilon_33       0.022052  0.017714  0.014127  
epsilon_43       0.004115  0.002831  0.001372  
epsilon_44       0.004446  0.002659  0.000822  
epsilon_45       0.004630  0.001712  0.000020  
...                   ...       ...       ...  
epsilon_2342475  0.004369  0.002162  0.000066  
epsilon_2342476  0.004371  0.002163  0.000065  
epsilon_2342523  0.004410  0.002597  0.000774  
epsilon_2342524  0.004360  0.002442  0.000533  
epsilon_2342525  0.004437  0.002647  0.000844  

[54232 rows x 29 columns]

In [103]:
def lhs_method(sdf):
    LHS=[]
    sampler = qmc.LatinHypercube (d=2)
    for group in sdf.groupby('classe'):
        plage=group[1].describe().loc[['min','max']][['300.0','3630.0']]
        sample = sampler.random (n=10)
        sample[:,0]=sample[:,0]*plage.loc['min']['300.0']+(1-sample[:,0])*plage.loc['max']['300.0']
        sample[:,1]=sample[:,1]*plage.loc['min']['3630.0']+(1-sample[:,1])*plage.loc['max']['3630.0']
        LHS.append(sample)
    return LHS
LHS=lhs_method(sdf)
LHS

[array([[0.01530799, 0.01265394],
        [0.01466785, 0.01345993],
        [0.01725978, 0.01377645],
        [0.01650213, 0.01300532],
        [0.01581324, 0.01252735],
        [0.01455919, 0.01201246],
        [0.01610183, 0.01274836],
        [0.01403464, 0.01369091],
        [0.01548708, 0.01233632],
        [0.01671593, 0.01321252]]),
 array([[0.02274756, 0.01506632],
        [0.02363179, 0.01586631],
        [0.01903621, 0.01707437],
        [0.02193376, 0.01662413],
        [0.02345586, 0.02049997],
        [0.02162919, 0.01973528],
        [0.02023682, 0.01791505],
        [0.01942872, 0.01819   ],
        [0.02101459, 0.01894602],
        [0.01808737, 0.0145326 ]]),
 array([[0.03408531, 0.04367934],
        [0.03191936, 0.02941699],
        [0.04930749, 0.04526274],
        [0.0410549 , 0.03259832],
        [0.03674138, 0.04196047],
        [0.03601146, 0.0373452 ],
        [0.04242072, 0.03968393],
        [0.04436456, 0.03433765],
        [0.03871136, 0.03578011],
        [0

# LHS method

In [48]:
from scipy.stats import qmc

In [75]:
sampler = qmc.LatinHypercube (d=2)
sample = sampler.random (n=10)
sample

array([[0.53857961, 0.3236865 ],
       [0.7496207 , 0.69647806],
       [0.37980367, 0.03020755],
       [0.03615863, 0.47945581],
       [0.97583279, 0.73300185],
       [0.45036704, 0.87715897],
       [0.63236392, 0.94960571],
       [0.15785631, 0.20156248],
       [0.26378086, 0.55745315],
       [0.85906226, 0.16677309]])

In [79]:
sample[:,0]=sample[:,0]*plage.loc['min']['300.0']+(1-sample[:,0])*plage.loc['max']['300.0']
sample[:,1]=sample[:,1]*plage.loc['min']['3630.0']+(1-sample[:,1])*plage.loc['max']['3630.0']
sample

array([[0.01609109, 0.01341139],
       [0.01561333, 0.01286286],
       [0.01645053, 0.01384322],
       [0.01722847, 0.01318219],
       [0.01510123, 0.01280911],
       [0.01629078, 0.012597  ],
       [0.01587878, 0.0124904 ],
       [0.01695297, 0.01359109],
       [0.01671318, 0.01306742],
       [0.01536558, 0.01364228]])